Fix out-of-scope usage of `IMPL_VERSION` in Dockerfiles
Docker build args are scoped to a particular build stage (`FROM`).
By starting a new one, previous args go out of scope. Ensure that
`IMPL_VERSION` is available inside the actual build by adding an
additional `ARG` directive, as well as a check to confirm that the
argument is set.

diff --git a/docker/dpcpp/Dockerfile b/docker/dpcpp/Dockerfile
--- a/docker/dpcpp/Dockerfile
+++ b/docker/dpcpp/Dockerfile
@@ -3,6 +3,9 @@ ARG IMPL_VERSION
 
 FROM khronosgroup/sycl-cts-ci:common
 
+ARG IMPL_VERSION
+RUN test -n "$IMPL_VERSION" || ( echo "Error: IMPL_VERSION is not set"; exit 1 )
+
 RUN git clone https://github.com/intel/llvm.git \
       --branch=sycl --single-branch --shallow-since=2021-09-01 \
       --recurse-submodules /tmp/dpcpp && \
diff --git a/docker/hipsycl/Dockerfile b/docker/hipsycl/Dockerfile
--- a/docker/hipsycl/Dockerfile
+++ b/docker/hipsycl/Dockerfile
@@ -3,6 +3,9 @@ ARG IMPL_VERSION
 
 FROM khronosgroup/sycl-cts-ci:common
 
+ARG IMPL_VERSION
+RUN test -n "$IMPL_VERSION" || ( echo "Error: IMPL_VERSION is not set"; exit 1 )
+
 RUN export DEBIAN_FRONTEND=noninteractive && \
     apt update && \
     apt install -y --no-install-recommends \
